### ISSUE TITLE
libfdt.FdtException: pylibfdt error -9: FDT_ERR_BADMAGIC

### ISSUE THREAD

**Issue by dieselnutjob** [msm8916-mainline/linux-mdss-dsi-panel-driver-generator#22]
Hi
I tried to use lmdpdg.py on both a binary dtb and the decompiled version (I think that's what you mean by dtbs).
I installed pylibfdt first by using this https://github.com/devicetree-org/pylibfdt
This is the output I get:-
`$ ./lmdpdg.py rk3566_tablet2.dts
Parsing: rk3566_tablet2.dts
Traceback (most recent call last):
  File "./lmdpdg.py", line 72, in <module>
    fdt = Fdt2(f.read())
  File "/usr/local/lib/python3.8/dist-packages/pylibfdt-1.6.1-py3.8-linux-x86_64.egg/libfdt.py", line 174, in __init__
    check_err(fdt_check_header(self._fdt));
  File "/usr/local/lib/python3.8/dist-packages/pylibfdt-1.6.1-py3.8-linux-x86_64.egg/libfdt.py", line 132, in check_err
    raise FdtException(val)
libfdt.FdtException: pylibfdt error -9: FDT_ERR_BADMAGIC`

what did I get wrong please?

**Comment by stephan-gh** [comment]
You need to give it the binary dtb, not the source one. Also note that this generator only supports Qualcomm platforms. It won't work for a Rockchip device, sorry :(

**Comment by dieselnutjob** [comment]
Yep I think I have realised that in the last few minutes.  There is an article here https://chowdera.com/2022/03/202203242230208988.html that describes the rockchip mangling process.  Maybe someone could make something like your code but make it work for Rockchip.... hint, hint....
