### ISSUE TITLE
dts: Adding device tree for drm panel

### ISSUE THREAD

**Issue by Jaimin19parmar** [msm8916-mainline/linux-mdss-dsi-panel-driver-generator#26]
**Panel: raspberry pi 7-inch display
DSI connection two-lane
Configurable through i2c**

**My changes:**
1. Adding port in mdss_dsi0 node.
`                ports {
                                        port@0 {
                                                reg = <0>;
                                                mdss_dsi0_out: endpoint {
                                                        remote-endpoint = <&mdss_dsi0_in>;
                                                };
                                        };
                                };

`
2. Adding Panel configuration.
`&qupv3_se2_i2c {
        status = "ok";
        qcom,clk-freq-out = <100000>;
        rpi-display@45 {
                status = "ok";
                compatible = "raspberrypi,7inch-touchscreen-panel";
                reg = <0x45>;
                port {
                        mdss_dsi0_in: endpoint {
                                remote-endpoint = <&mdss_dsi0_out>;
                        };
                };
        };

        rpi-touchscreen@38 {
                status = "ok";
                compatible = "rpi,ft5406";
                reg = <0x38>;
                touchscreen-size-x = <800>;
                touchscreen-size-y = <480>;
                rotate_180 = <0>;
        };

};
`
--> Compilation successful without any warning or error.
--> Gives runtime error.
`[    4.162367] i2c /dev entries driver
[    4.167272] i2c_geni 4a80000.i2c: Bus frequency is set to 400000Hz
[    4.175085] i2c_geni 4a88000.i2c: Bus frequency is set to 400000Hz
[    4.183741] <<GTP-INF>>[gt1x_ts_probe:614] GTP Driver Version: V1.6<2017/12/11>,slave addr:5dh
[    4.192537] i2c i2c-1: of_i2c: modalias failure on /soc/i2c@4a88000/rpi-display@45
[    4.200168] i2c i2c-1: Failed to create I2C device for /soc/i2c@4a88000/rpi-display@45
[    4.208110] i2c i2c-1: of_i2c: modalias failure on /soc/i2c@4a88000/rpi-touchscreen@38
[    4.216070] i2c i2c-1: Failed to create I2C device for /soc/i2c@4a88000/rpi-touchscreen@38
`

Let me know possible causes.
Thanks

**Comment by stephan-gh** [comment]
Hi,

linux-mdss-dsi-panel-driver-generator allows generating display panel drivers for the "mainline"/"upstream" Linux kernel (taken directly from https://www.kernel.org/). It looks like you are using a modified "downstream" Linux kernel from Qualcomm. Please ask them (or whoever provided the kernel source to you) for help instead.

Thanks!
