### ISSUE TITLE
Cannot send DSI commands in unprepare callback

### ISSUE THREAD

**Issue by barni2000** [msm8916-mainline/linux-mdss-dsi-panel-driver-generator#44]
dsi commands in unprepare cause some error message it not cause any serious issue but it seems dsi commands are not allowed in this callback.
```
[   92.322564] panel-td4320-boeplus c994000.dsi.0: sending command 0x28 failed: -22
[   92.322635] panel-td4320-boeplus c994000.dsi.0: Failed to un-initialize panel: -22
```

**Comment by barni2000** [comment]
Partial fixed in 6.10

**Comment by z3ntu** [comment]
Do you have any reference for patches in Linux for this? Since this topic seems to come up once in a while, it'd be good to have some links.

**Comment by barni2000** [comment]
> Do you have any reference for patches in Linux for this? Since this topic seems to come up once in a while, it'd be good to have some links.

Yes, https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/drivers/gpu/drm/drm_bridge.c?h=next-20240510&id=e18aeeda0b6905c333df5a0566b99f5c84426098

this fixing the ordering issue but this https://github.com/msm8916-mainline/linux/commit/a0f70d428d07382892923c35918ac1d5e9c6dce4 commit also needed for msm8953 (sdm632, sdm450), msm8996 with add same property for dpu_encoder i don't tested other SOCs yet, but maybe sdm660 will also need this.
